CREATE TABLE T_ORDER(
 ID BIGINT PRIMARY KEY AUTO_INCREMENT,
 CPF VARCHAR(200) NOT NULL,
 TOTAL DECIMAL(10,2),
 ADDRESS_ID BIGINT
)engine=InnoDB;

ALTER TABLE T_ORDER ADD CONSTRAINT FK_ADDRESS_T_ORDER FOREIGN KEY(ADDRESS_ID) REFERENCES ADDRESS (ID);