spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sprint6?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: Compass123
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: false

  # Producer properties
  kafka:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      group-id: group_id
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        properties:
          spring:
            json:
              add:
                type:
                  headers: 'false'
kafka: producer.bootstrap-servers=127.0.0.1:9092
topic:
  name:
    producer: topic.order.history
  
  # Common Kafka Properties
  auto:
    create:
      topics:
        enable: 'true'
