spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sprint6?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: Compass123
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: false

  # Producer properties
  kafka:
    producer:
      value-serializer: org.apache.kafka.common.serialization.JsonDeserializer
      group-id: group_id
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
kafka: producer.bootstrap-servers=127.0.0.1:9092
topic:
  name:
    producer: topico.comando.order
  
  # Common Kafka Properties
  auto:
    create:
      topics:
        enable: 'true'